### ISSUE TITLE
Create Release Script

### ISSUE THREAD

**Issue by john-science** [theJollySin/DecafMUD#17]
This project needs a release script.  The script should:

* minify the JavaScript
* minify the CSS

I think Google Closure would only half-solve this problem.

**Comment by theJollySin** [comment]
Here is a handy link to the Closure JS Compliler:

https://github.com/google/closure-compiler

**Comment by theJollySin** [comment]
Is this possible?

https://github.com/google/closure-stylesheets

**Comment by theJollySin** [comment]
Yeah, let's minify CSS with Google Closure as well:

https://github.com/google/closure-stylesheets/releases
